### ISSUE TITLE
the custom css file dont applied when enable css and js loader and relead it again

### ISSUE THREAD

**Issue by massdx** [glennraya/vscode-settings-json#1]
the custom css file dont applied when enable css and js loader and relead it again 
![image](https://github.com/user-attachments/assets/c4080043-1f64-4bfd-b5a0-078621254b05)

**Comment by glennraya** [comment]
Hi, I also encountered this error before. Try to change the ownership of the css/js files. You need to own them.

**Comment by massdx** [comment]
thanks it work

**Comment by glennraya** [comment]
You're welcome!
