### ISSUE TITLE
Loader isn't working on windows

### ISSUE THREAD

**Issue by SyedMohammadAnas** [glennraya/vscode-settings-json#12]
I changed the ownership to myself, wrote the file path perfectly, ran vscode as administrator, and I removed the read-only checkbox but the css and js file wont load at all, it did for a couple of minutes and it vanished after that

**Comment by glennraya** [comment]
Hi, it would be helpful if you can take screenshots of your setup (settings.json), or the issue you encountered.

**Comment by SyedMohammadAnas** [comment]
![Screenshot 2024-09-05 160320](https://github.com/user-attachments/assets/ce8e6fd2-7af4-4f72-8ca8-102d038e85a8)
![Screenshot 2024-09-05 160635](https://github.com/user-attachments/assets/da7999e0-77e6-4bc8-95e1-2316aa5d77d8)
I tried Enabling it Reloading it closing and opening vs code in admin privileges multiple, restarted my PC several times, reinstalled the extension, everything but it still wont apply

**Comment by glennraya** [comment]
There might be something else at play here. This is a weird issue. Try relocating your files from C:\ to somewhere like C:\Users\your-account.

**Comment by SyedMohammadAnas** [comment]
It isn't working at all, I gave the whole C drive permission to my user but the C:\Users\RayanSyed folder still reverts back to the "Read-only" attribute

**Comment by glennraya** [comment]
If the file keeps getting the read-only attribute, it might be an issue with your OS/computer now. Normally, it should suffice to run vs code as admin to make it work,  a lot of people in the YouTube comment section only need to perform that step to make it work. Of course, different computers have different setups so I can't really for sure in your case.
