### ISSUE TITLE
Text in Cmd Pallette slightly blurry

### ISSUE THREAD

**Issue by stephenstack** [glennraya/vscode-settings-json#14]
Great work on this. I've totally adopted all your chnages, hope to do more. Its changed the look and feel of VsCode for the better.

One small thing, i hope you can see. Text in my command palette is slightly blurred, any idea? It is 'slight' but enough for me to notice.

![{A20728CC-7966-4900-8A2E-0DE95C60719A}](https://github.com/user-attachments/assets/2c37d964-0590-4166-be46-080a26452b6d)

**Comment by glennraya** [comment]
I believe that has something to do with your screen's scaling settings. It doesn't have anything to do with the extensions I think.

**Comment by stephenstack** [comment]
I'll investigate further and report back if i find something. Thanks

**Comment by stephenstack** [comment]
Located the answer, here


I fixed this issue by subtracting 0.5px from the value of the Y-axis. So instead of doing:
.quick-input-widget {
   transform: translateY(-50%);
I did this:

.quick-input-widget {
	transform: translateY(calc(-50% - 0.5px)) !important;


[This solved it for me and I find this a cleaner solution then fiddling around with the percentage or using Javascript.](https://stackoverflow.com/questions/27385126/chrome-font-appears-blurry#comment72382325_42613744)

**Comment by Karlito05** [comment]
Hi. I have looked into this a bit more and found that when you do
`transform: translateY(round(-50%)) !important;`
it works better. Because the problem was that you end up with subpixel values so subtracting .5px worked only half of the time. This ensures that you got a whole value every time.

**Comment by Karlito05** [comment]
Hi i have found a better solution.

I have used `transform: translateY(round(up, -50%, 1px)) !important;` and it fixed my problem. I belive the problem was that i was ending up with a wierd subpixel value so using  `transform: translateY(calc(-50% - 0.5px)) !important;` fixed it only half of the time.
