### ISSUE TITLE
Windows blur issue.

### ISSUE THREAD

**Issue by mrjxtr** [glennraya/vscode-settings-json#15]
# Windows blur issue.

Hey Glenn 👋🏼

I appreciate your replying to the YouTube comments to solve my problem. I wanted to send you context here so we won't need to go back and forth in the comment section and I can add screenshots.

## Here is what I've got so far.

![image](https://github.com/user-attachments/assets/56ad2660-d0ae-40c8-8682-645749c8446e)

and as for the script, I created my file but the code inside is just simply copy and paste of what you have in your repo. [This file](https://github.com/glennraya/vscode-settings-json/blob/main/vscode-script.js)

### as for my custom CSS

![image](https://github.com/user-attachments/assets/6d260a7c-4615-4ad7-9c4b-3bc9e0d747bf)

### This is the result after reloading and restarting vs code.

![image](https://github.com/user-attachments/assets/1d75b697-a2ce-43a8-84e1-87669c4730d3)

As you can see, still no blur.

**Comment by glennraya** [comment]
Hello, I can see that you placed the files under "AppData/Roaming..." directory, try to place the files under other directories like in the desktop or documents folder so it would be like

```
file:///C:/Users/MyUserName/Documents/custom.css
```

**Comment by mrjxtr** [comment]
> Hello, I can see that you placed the files under "AppData/Roaming..." directory, try to place the files under other directories like in the desktop or documents folder so it would be like
> 
> ```
> file:///C:/Users/MyUserName/Documents/custom.css
> ```

Still no luck... I moved it to file:///C:/../Documents, file:///C:/../Desktop and even file:///D:/../. I tried to run vscode in admin mode checked the ownership, and renamed the file. trusted all these folders. But nothing worked.

![image](https://github.com/user-attachments/assets/e15f8730-0394-4c9a-a149-6e1af7e04809)

**Comment by glennraya** [comment]
That's weird, I'm pretty sure though, that something else is causing this issue. I experienced before that other customization plugin was conflicting with CSS and JS Loader like the APC++ extension. I don't know about your particular setup, but I think some other extension is conflicting with CSS and JS Loader.

**Comment by mrjxtr** [comment]
I don't have another extension for customization tho, but your probably right... Something might be conflicting with the CSS and JS loader... I'll continue to tinker with the settings.json and the custom.css files and see if the issue is there.

**Comment by mrjxtr** [comment]
> To make sure when you press `Ctrl + shift + p` getting blur background, you have to make sure below code is correctly in your `custom.css`
> 
> ```
> #command-blur {
>     position: absolute;
>     width: 100%;
>     height: 100%;
>     background: rgba(0, 0, 0, .15);
>     top: 0;
>     left: 0;
>     backdrop-filter: blur(8px);
> }
> ```
> 
> ![241023_22h07m59s_screenshot](https://private-user-images.githubusercontent.com/1939446/379309109-16d45da6-b479-4752-b117-81e6445c562b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MjUwMTIsIm5iZiI6MTcyOTcyNDcxMiwicGF0aCI6Ii8xOTM5NDQ2LzM3OTMwOTEwOS0xNmQ0NWRhNi1iNDc5LTQ3NTItYjExNy04MWU2NDQ1YzU2MmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMjMwNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdlM2Y4YzQwNjczNTJjZTIwYzY1ODYzZTllNDVmNTlkMTJhM2I3MTY3ZGFlZjNiMThhZWRjYzNmMDc2MjllYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fydzFeJVopraev0SaKbwcIJfupJsWeDxJX5C4ug_cfY)

# THIS SOLVES THE PROBLEM! THANKS!

![image](https://github.com/user-attachments/assets/cfa97dcc-0810-4bc9-96df-abb5e9f8fae3)

![image](https://github.com/user-attachments/assets/d2cfb478-84e9-4455-ad2c-fd245586fcbe)
