### ISSUE TITLE
the broken title bar

### ISSUE THREAD

**Issue by Perigrino** [glennraya/vscode-settings-json#18]
I followed your tutorial in the video, and everything worked perfectly except for one issue—could you help me fix the broken title bar?
![Screenshot 2024-11-14 at 12 14 02 AM](https://github.com/user-attachments/assets/da9eaed4-3743-440e-9f37-5d30725e0990)

**Comment by glennraya** [comment]
Hi, you only need to properly target the element that controls the styling of the tab. Sometimes you may need a trial and error to properly select the element that controls the tab.

**Comment by Perigrino** [comment]
I think i found a solution and got it fixed, thanks

**Comment by glennraya** [comment]
That's good to know.
