### ISSUE TITLE
VS Code on linux cant do the same on command palette.

### ISSUE THREAD

**Issue by thyeun** [glennraya/vscode-settings-json#2]
Any ideal how to make the command palette same from your youtube? 

As i noticed that you are under macOS, but after follow from your youtube clip, look like VS code on linux are not possible to do the same for the command palette.  (same goes to the art.svg)

As you can see from the image below.

![240802_10h19m52s_screenshot](https://github.com/user-attachments/assets/3b2c2f3b-616e-45f0-ab6b-00c1a1b03e1d)

**Comment by glennraya** [comment]
Hi, it is possible on every operating system because it is just a regular CSS file responsible for modifying VS Code’s UI. If the changes are not reflecting, you may need to take ownership of the CSS/JS file you created for the changes to take effect.

**Comment by glennraya** [comment]
You can read more about this from the documentation of "Custom CSS and JS Loader" extension.

**Comment by thyeun** [comment]
Understand, might something that im not done it correctly.
