### ISSUE TITLE
blur doesn't work on tabs border

### ISSUE THREAD

**Issue by veshall** [glennraya/vscode-settings-json#4]
blur effect of command palette doesn't work on border of active tab and on vertical separator line.
![Screenshot 2024-08-04 001957](https://github.com/user-attachments/assets/6067d107-a3f4-4762-acdf-cd2ee5422b4a)

**Comment by glennraya** [comment]
I don't use tabs so I didn't see this. But I will check this out to see if there's a solution. Thanks.
