### ISSUE TITLE
Some recommendation on Read me changes and an error during file loading

### ISSUE THREAD

**Issue by arg387** [glennraya/vscode-settings-json#8]
# Recommendation
When i was checking your custom css files i have noticed that for this part of the code 
 `.mtk3 {
  font-family: 'Monaspace Radon', monospace !important;
}`
there is no instruction to install monaspace Radon font. I think you should add this in the read me file.

# Error
![Screenshot 2024-08-07 142707](https://github.com/user-attachments/assets/a0c7e240-fe45-464c-b408-4613b82ae7eb)
I have followed all the instruction given to the extension and read me file but this error is still showing.  Please help.

**Comment by glennraya** [comment]
Actually, it is assumed that the person already knows that the font is already installed on the person's machine.

**Comment by arg387** [comment]
Alright but can you tell me why is this error happening and how to solve it?

**Comment by glennraya** [comment]
That error popup is expected since we have inserted our custom css/js files to VS Code, you just need to not show the message again by clicking the "don't show this message" again from the gear icon. This is actually mentioned in the extension's docs.
